exports.BOOTSTRAP          = 'BOOTSTRAP/';
exports.SIGNIN             = 'USERS/SIGNIN';
exports.SIGNIN_SUCCESS     = 'USERS/SIGNIN:SUCCESS';
exports.SIGNIN_ERROR       = 'USERS/SIGNIN:ERROR';
exports.SIGNIN_FORM_CHANGE = 'USERS/SIGNIN:FORM_CHANGE';

exports.SIGNUP             = 'USERS/SIGNUP';
exports.SIGNUP_SUCCESS     = 'USERS/SIGNUP:SUCCESS';
exports.SIGNUP_ERROR       = 'USERS/SIGNUP:ERROR';
exports.SIGNUP_FORM_CHANGE = 'USERS/SIGNUP:FORM_CHANGE';
exports.SIGNUP_FORM_FIELD_ERROR = 'USERS/SIGNUP:FORM_FIELD_ERROR';

exports.CHAT_SEND_MESSAGE           = 'CHAT/SEND_MESSAGE';
exports.CHAT_SEND_MESSAGE_SUCCESS   = 'CHAT/SEND_MESSAGE:SUCCESS';
exports.CHAT_SEND_MESSAGE_ERROR     = 'CHAT/SEND_MESSAGE:ERROR';

exports.SIGNOUT                 = 'USERS/SIGNOUT';
exports.SIGNOUT_SUCCESS         = 'USERS/SIGNOUT:SUCCESS';
exports.SIGNOUT_ERROR           = 'USERS/SIGNOUT:ERROR';
exports.SIGNOUT_GLOBAL          = 'USERS/SIGNOUT_GLOBAL';
exports.SIGNOUT_GLOBAL_SUCCESS  = 'USERS/SIGNOUT_GLOBAL:SUCCESS';
exports.SIGNOUT_GLOBAL_ERROR    = 'USERS/SIGNOUT_GLOBAL:ERROR';
exports.AUTH                    = 'USERS/AUTH';
exports.AUTH_SUCCESS            = 'USERS/AUTH:SUCCESS';
exports.AUTH_ERROR              = 'USERS/AUTH:ERROR';
